/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

import * as THREE from "three";

const Chair_nella = (props) => {
  const { nodes, materials } = useGLTF("./models/chair_nella-transformed.glb");

  const leatherTextureProps = useTexture({
    map: "./textures/leather/Leather_008_Base_Color.jpg",
    normalMap: "./textures/leather/Leather_008_Normal.jpg",
    roughnessMap: "./textures/leather/Leather_008_Roughness.jpg",
    aoMap: "./textures/leather/Leather_008_Ambient_Occlusion.jpg",
  });

  leatherTextureProps.map.repeat.set(1, 1);
  leatherTextureProps.normalMap.repeat.set(1, 1);
  leatherTextureProps.roughnessMap.repeat.set(1, 1);
  leatherTextureProps.aoMap.repeat.set(1, 1);

  leatherTextureProps.map.wrapS =
    leatherTextureProps.map.wrapT =
    leatherTextureProps.normalMap.wrapS =
    leatherTextureProps.normalMap.wrapT =
    leatherTextureProps.roughnessMap.wrapS =
    leatherTextureProps.roughnessMap.wrapT =
    leatherTextureProps.aoMap.wrapS =
    leatherTextureProps.aoMap.wrapT =
      THREE.RepeatWrapping;

  const woodTextureProps = useTexture({
    map: "./textures/wood/Wood_027_basecolor.jpg",
    normalMap: "./textures/wood/Wood_027_normal.jpg",
    roughnessMap: "./textures/wood/Wood_027_roughness.jpg",
    aoMap: "./textures/wood/Wood_027_ambientOcclusion.jpg",
  });

  woodTextureProps.map.repeat.set(1, 1);
  woodTextureProps.normalMap.repeat.set(1, 1);
  woodTextureProps.roughnessMap.repeat.set(1, 1);
  woodTextureProps.aoMap.repeat.set(1, 1);

  woodTextureProps.map.wrapS =
    woodTextureProps.map.wrapT =
    woodTextureProps.normalMap.wrapS =
    woodTextureProps.normalMap.wrapT =
    woodTextureProps.roughnessMap.wrapS =
    woodTextureProps.roughnessMap.wrapT =
    woodTextureProps.aoMap.wrapS =
    woodTextureProps.aoMap.wrapT =
      THREE.RepeatWrapping;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.SM_Metal.geometry}
        material={materials["Aluminium Clean.001"]}
      />
      <mesh geometry={nodes.SM_Seat.geometry}>
        <meshStandardMaterial {...leatherTextureProps} />
      </mesh>
      <mesh geometry={nodes.SM_Feet.geometry}>
        <meshStandardMaterial {...woodTextureProps} />
      </mesh>
    </group>
  );
};

useGLTF.preload("./models/chair_nella-transformed.glb");

export default Chair_nella;
