/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const  Mono = (props) => {
  const { nodes, materials } = useGLTF('./models/mono-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SM_Metal.geometry} material={materials['Aluminium Clean.002']} position={[0, 0.66, -0.21]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0} />
      <mesh geometry={nodes.SM_Seat.geometry} material={materials['Fabric Linen.002']} position={[0, 0.41, 0.05]} scale={0} />
      <mesh geometry={nodes.SM_Feet.geometry} material={materials['Walnut Semigloss.002']} position={[-0.23, 0, 0.25]} rotation={[0, -1.57, 0]} scale={0} />
      <mesh geometry={nodes.Suzanne.geometry} material={nodes.Suzanne.material} />
    </group>
  )
}

useGLTF.preload('./models/mono-transformed.glb')

export default Mono;